### ISSUE TITLE
add support for data classes

### ISSUE THREAD

**Issue by jans-de** [CJCrafter/PythonGettersAndSetters#2]
Please add support for data classes.

Given a class Data with the attributes `field_id` and `name` like this:
```
@dataclass(frozen=True)
class Data:
    field_id: str
    name: str
```

When I tried to generate the getter, setter and deleter for `Data` I got the error: Could not find \_\_init\_\_ method in Data!

**Comment by CJCrafter** [comment]
https://docs.python.org/3/library/dataclasses.html

will do
